### ISSUE TITLE
sign function dosent take secret registred in module

### ISSUE THREAD

**Issue by omarberrami** [nestjs/jwt#1032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

After using registerAsync or register at module level with secret, that seem to be undefined at sign methode.

- you can check gist of the module here : https://gist.github.com/omarberrami/d6bf3eefee8e967b836a44b10e2679ff

- you can check the service gist here : https://gist.github.com/omarberrami/f91140240bac674e03fdde364a217875

### Minimum reproduction code

https://gist.github.com/omarberrami/d6bf3eefee8e967b836a44b10e2679ff   ,     https://gist.github.com/omarberrami/f91140240bac674e03fdde364a217875

### Steps to reproduce

follow nest documentation to implement jwt, and sign function wil trigger an error

### Expected behavior

the secred passed to module need to be availeble at signe methode without ovverding it againat signe methode level

### Package version

9.0.0

### NestJS version

9.0.1

### Node.js version

12.22.10

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

`secretOrPrivateKey must have a value
    at Object.module.exports [as sign] (/Users/cloudeco/Documents/bee-in/api-app-itiforums/node_modules/jsonwebtoken/sign.js:107:20)
    at JwtService.sign (/Users/cloudeco/Documents/bee-in/api-app-itiforums/node_modules/@nestjs/jwt/dist/jwt.service.js:29:20)
    at AuthService.loginWithCredentials (/Users/cloudeco/Documents/bee-in/api-app-itiforums/src/auth/auth.service.ts:45:44)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at AuthController.authByEmailAndPass (/Users/cloudeco/Documents/bee-in/api-app-itiforums/src/auth/auth.controller.ts:11:12)
    at /Users/cloudeco/Documents/bee-in/api-app-itiforums/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /Users/cloudeco/Documents/bee-in/api-app-itiforums/node_modules/@nestjs/core/router/router-proxy.js:9:17`

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
