### ISSUE TITLE
TypeError: metatype is not a constructor

### ISSUE THREAD

**Issue by KenySushant** [nestjs/jwt#173]
Hi Team,

My code was running properly and all of a sudden I'm getting this error.

`[Nest] 10348   - 16/02/2020, 11:14:40 pm   [ExceptionHandler] metatype is not a constructor +17ms
TypeError: metatype is not a constructor
    at Injector.instantiateClass (C:\Users\susha\Documents\Nest.js\Task Management\node_modules\@nestjs\core\injector\injector.js:288:19)
    at callback (C:\Users\susha\Documents\Nest.js\Task Management\node_modules\@nestjs\core\injector\injector.js:75:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Injector.resolveConstructorParams (C:\Users\susha\Documents\Nest.js\Task Management\node_modules\@nestjs\core\injector\injector.js:116:24)
    at async Injector.loadInstance (C:\Users\susha\Documents\Nest.js\Task Management\node_modules\@nestjs\core\injector\injector.js:79:9)
    at async Injector.loadInjectable (C:\Users\susha\Documents\Nest.js\Task Management\node_modules\@nestjs\core\injector\injector.js:32:9)
    at async Promise.all (index 0)
    at async InstanceLoader.createInstancesOfInjectables (C:\Users\susha\Documents\Nest.js\Task Management\node_modules\@nestjs\core\injector\instance-loader.js:57:9)
    at async C:\Users\susha\Documents\Nest.js\Task Management\node_modules\@nestjs\core\injector\instance-loader.js:28:13
    at async Promise.all (index 6)`

I've tried installing and uninstalling the node_modules it still didn't help.

I can't find the problem too using the error stack.

Could anyone please check where is it breaking?

This is the [link](https://github.com/KenySushant/Task-Management.git) to my repository in which I'm facing the issue.

Thanks!

**Comment by KenySushant** [comment]
Hi Team, this worked after I re-built the project. I don't understand what's the problem!

**Comment by painoBoy** [comment]
Me too

**Comment by kudryaA** [comment]
Me too
